CREATE TABLE IF NOT EXISTS "class_schedules" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"class_id" INTEGER NOT NULL,
	"room_id" INTEGER NOT NULL,
	"day_of_week" SMALLINT NOT NULL CHECK(day_of_week >= 0 AND day_of_week <= 6),
	"start_time" TIMESTAMPTZ NOT NULL,
	"end_time" TIMESTAMPTZ NOT NULL,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "class_teachers" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"teacher_id" INTEGER NOT NULL,
	"class_id" INTEGER NOT NULL,
	"role_in_class" VARCHAR(50) NOT NULL DEFAULT 'Main' CHECK(role_in_class IN ('Main', 'Assistant', 'Substitute')),
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "classes" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"course_id" INTEGER NOT NULL,
	"level" VARCHAR(255),
	"name" VARCHAR(200) NOT NULL,
	"slug_name" VARCHAR(255) NOT NULL,
	"duration_weeks" SMALLINT NOT NULL,
	"base_price" NUMERIC(10,2) NOT NULL,
	"material_fee" NUMERIC(10,2) DEFAULT 0.00,
	"max_capacity" SMALLINT NOT NULL,
	"start_date" TIMESTAMPTZ NOT NULL,
	"end_date" TIMESTAMPTZ NOT NULL,
	-- Upcoming, Active, Completed, Cancelled
	"status" VARCHAR(20) NOT NULL DEFAULT 'Upcoming' CHECK(status IN ('Upcoming', 'Active', 'Completed', 'Cancelled')),
	"note" TEXT,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "classes"."status" IS 'Upcoming, Active, Completed, Cancelled';


CREATE TABLE IF NOT EXISTS "courses" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"subject_id" INTEGER NOT NULL,
	"name" VARCHAR(200) NOT NULL,
	"slug_name" VARCHAR(255) NOT NULL UNIQUE,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "subjects" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(200) UNIQUE,
	"slug_name" VARCHAR(255) UNIQUE,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "users" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"username" VARCHAR(255) NOT NULL,
	"password" VARCHAR(255) NOT NULL,
	"date_of_birth" DATE NOT NULL,
	"last_name" VARCHAR(255) NOT NULL,
	"first_name" VARCHAR(255) NOT NULL,
	"address" VARCHAR(500),
	"email" VARCHAR(255) UNIQUE,
	"phone_number" VARCHAR(20),
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);


CREATE INDEX "users_index_first-last-name"
ON "users" ("first_name", "last_name");
CREATE INDEX "users_index_last-first-name"
ON "users" ("last_name", "first_name");

CREATE TABLE IF NOT EXISTS "teachers" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"expertise" JSONB NOT NULL,
	"qualification" JSONB NOT NULL,
	"hire_date" TIMESTAMPTZ NOT NULL,
	"salary_basic" NUMERIC(10,2) NOT NULL,
	"allowances" JSONB,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "students" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"parent_id" INTEGER,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "parents" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "enrollments" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"student_id" INTEGER NOT NULL,
	"class_id" INTEGER NOT NULL,
	"enroll_date" TIMESTAMPTZ NOT NULL,
	"status" VARCHAR(25) DEFAULT 'Active' CHECK(status IN ('Active', 'Completed', 'Dropped')),
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "class_promotions" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"class_id" INTEGER NOT NULL,
	"promotion_id" INTEGER NOT NULL,
	"promo_start_date" TIMESTAMPTZ NOT NULL,
	"promo_end_date" TIMESTAMPTZ NOT NULL,
	"max_applicants" INTEGER,
	"is_active" BOOLEAN NOT NULL DEFAULT True,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "promotions" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"promo_code" VARCHAR(20) UNIQUE,
	"discount_type" VARCHAR(25) NOT NULL CHECK(discount_type IN ('Percent', 'Fixed')),
	"discount_value" NUMERIC(10,2) NOT NULL,
	"start_date" TIMESTAMPTZ NOT NULL,
	"end_date" TIMESTAMPTZ NOT NULL,
	"is_global" BOOLEAN NOT NULL DEFAULT true,
	"max_usage_limit" INTEGER,
	"status" VARCHAR(25) NOT NULL DEFAULT 'Active' CHECK(status IN ('Active', 'Inactive')),
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "rooms" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(50) NOT NULL UNIQUE,
	"location" VARCHAR(100) UNIQUE,
	"capacity" INTEGER NOT NULL CHECK(capacity > 0),
	"is_available" BOOLEAN NOT NULL DEFAULT true,
	"equipment_details" JSONB,
	"description" TEXT,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "permissions" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"name" VARCHAR(255) NOT NULL,
	"description" TEXT,
	-- Update các ràng buộc: 'classes', 'finance', 'users' ...
	"module" VARCHAR(50),
	-- Update các ràng buộc: read_all, read, delete, ...
	"action" VARCHAR(50),
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "permissions"."module" IS 'Update các ràng buộc: ''classes'', ''finance'', ''users'' ...';
COMMENT ON COLUMN "permissions"."action" IS 'Update các ràng buộc: read_all, read, delete, ...';


CREATE TABLE IF NOT EXISTS "roles" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	-- Update các ràng buộc: admin, student, teacher, ...
	"name" VARCHAR(255) NOT NULL,
	"description" TEXT,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);


COMMENT ON COLUMN "roles"."name" IS 'Update các ràng buộc: admin, student, teacher, ...';


CREATE TABLE IF NOT EXISTS "user_roles" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"user_id" INTEGER NOT NULL,
	"role_id" INTEGER NOT NULL,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);




CREATE TABLE IF NOT EXISTS "role_permissions" (
	"id" INTEGER NOT NULL UNIQUE GENERATED BY DEFAULT AS IDENTITY,
	"role_id" INTEGER NOT NULL,
	"permission_id" INTEGER NOT NULL,
	"created_at" TIMESTAMPTZ,
	"updated_at" TIMESTAMPTZ,
	PRIMARY KEY("id")
);



ALTER TABLE "teachers"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "students"
ADD FOREIGN KEY("parent_id") REFERENCES "parents"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "parents"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "courses"
ADD FOREIGN KEY("subject_id") REFERENCES "subjects"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "classes"
ADD FOREIGN KEY("course_id") REFERENCES "courses"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "class_schedules"
ADD FOREIGN KEY("class_id") REFERENCES "classes"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "class_teachers"
ADD FOREIGN KEY("teacher_id") REFERENCES "teachers"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "class_teachers"
ADD FOREIGN KEY("class_id") REFERENCES "classes"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "students"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE "class_promotions"
ADD FOREIGN KEY("class_id") REFERENCES "classes"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "class_promotions"
ADD FOREIGN KEY("promotion_id") REFERENCES "promotions"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "enrollments"
ADD FOREIGN KEY("student_id") REFERENCES "students"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "enrollments"
ADD FOREIGN KEY("class_id") REFERENCES "classes"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "class_schedules"
ADD FOREIGN KEY("room_id") REFERENCES "rooms"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "role_permissions"
ADD FOREIGN KEY("role_id") REFERENCES "roles"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "role_permissions"
ADD FOREIGN KEY("permission_id") REFERENCES "permissions"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "user_roles"
ADD FOREIGN KEY("role_id") REFERENCES "roles"("id")
ON UPDATE CASCADE ON DELETE CASCADE;
ALTER TABLE "user_roles"
ADD FOREIGN KEY("user_id") REFERENCES "users"("id")
ON UPDATE CASCADE ON DELETE CASCADE;